### ISSUE TITLE
What is the intended purpose for storing the sha1 hash of migration file source?

### ISSUE THREAD

**Issue by BGEggen** [ichensky/EntityFrameworkCore.Sqlite.Migrations#1]
Thanks for the nice, clean example for migrations!

I’m not seeing anything on the intended purpose for storing the sha1 hash of migration file source.  Can you elaborate on that for me?

Thank you

**Comment by ichensky** [comment]
Perhaps in the future it will be useful when researching, for example, if we want to find out if the migration code has changed.

**Comment by BGEggen** [comment]
Thanks for the explanation.
